name: Unit Tests

on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x, 20.x, 19.x]

    steps:
      - uses: action/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: action/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: npm install
        run: npm ci
      - name: tests
        run: npm test
